### ISSUE TITLE
Conversion from MG/ML to %

### ISSUE THREAD

**Issue by pyephyomaung** [lhncbc/ucum-lhc#4]
First of all, great package! I am not sure if this is the right place to report issue here. But I notice that conversion from `MG/ML` (usually used in RxNorm, eg. rxcui 861487) to `%` is giving the incorrect result as
```
0.5 mg/mL = 50000.00 %
```
The correct result should be 0.05 %

Thanks!

**Comment by pyephyomaung** [comment]
It seems that in drug, the concentration is assumed to be calculated in water so `MG/ML` would be `MG/G`. but since ucum does not assume that this conversion might not be valid so might as well throw an error.

**Comment by plynchnlm** [comment]
Thanks for reporting this issue.  It seems that using mg/g does give the expected 0.05 %.  I would have expected mg/mL report an error because strictly speaking it does not have the same dimensions as %.  Anyway, we will look into it, but probably will report an error rather than handling mL->g implicit conversions.  Are you able to work around the issue by using mg/g?

**Comment by plynchnlm** [comment]
Closing due to lack of input.  Please feel free to re-open if if you need further assistance.
